# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'AprilSkillTest' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

pod 'RealmSwift'
pod 'Alamofire'

  # Pods for AprilSkillTest

  target 'AprilSkillTestTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'AprilSkillTestUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
